### ISSUE TITLE
License key

### ISSUE THREAD

**Issue by nysthee** [datawire/devportal-content#4]
Hi, it seems the current license key in the repo is not valid anymore.

**Comment by richarddli** [comment]
Thank you for the bug report. You should be able to use a license key that you get from an Ambassador Edge Stack install. Have you tried this? Thanks!

**Comment by nysthee** [comment]
Hi Richard

Thanks I tried that but got a error validating license key from file /content/.devportal.license: invalid license key: unrecognized license key version "v2"



On 12 June 2020 at 13:45:49, Richard Li (notifications@github.com) wrote:

Thank you for the bug report. You should be able to use a license key that you get from an Ambassador Edge Stack install. Have you tried this? Thanks!

**Comment by richarddli** [comment]
Can you explain exactly how you're getting the license and how you're getting the error? The license key should not be installed this way and is installed automatically in the UI.
